;@author baran buzluk
LIST P=16F877A
INCLUDE <P16F877A.INC>
    ORG 0X00
    GOTO INIT
    ORG 0X04
    GOTO INTERRUPT
    
INIT:
    TEMP EQU 0X31   
  ;GENERAL SETTING
    BANKSEL TEMP
    MOVLW B'01100100'; 25 derecenin binary karşılığı
    MOVWF TEMP
  ;GENERAL SETTING END
  
  ;TRIS SETTINGS
    BANKSEL TRISA
    MOVLW 0xFF
    MOVWF TRISA
    CLRF TRISB
  ;TRIS SETTINGS *END*
  
  ;A/D CONVERT SETTINGS
    BANKSEL ADCON1
    MOVLW 0X0F
    MOVWF ADCON1
    BANKSEL ADCON0
    MOVLW 0XC1
    MOVWF ADCON0
  ;A/D  CONVERT SETTINGS *END*
    
  ;INTERRUP SETTINGS
    BANKSEL PIE1
    BSF PIE1,ADIE
    BANKSEL INTCON
    BSF INTCON,GIE
    BSF INTCON,PEIE
   ;INTERRUP SETTINGS *END*
   
CONVERT:
    TIME1 EQU 0X20
    BANKSEL TIME1
    MOVLW D'10'
    MOVWF TIME1
DONGU_1:
    DECFSZ TIME1,F
    GOTO DONGU_1
    BANKSEL 0X00
    
    BSF ADCON0,GO; 
    GOTO CONVERT

INTERRUPT:
    BTFSS PIR1,ADIF 
    RETFIE	   
    BCF PIR1,ADIF   
    BANKSEL 0X00
    ;ENGINE CONTROL SETTING
    MOVFW TEMP 
    SUBWF ADRESH,W
    BTFSC STATUS,Z
    GOTO STOP
    BTFSC STATUS,C
    BSF PORTB,RB0
    BTFSS STATUS,C
    BCF PORTB,RB0
    BTFSC STATUS,C
    BCF PORTB,RB1
    BTFSS STATUS,C
    BSF PORTB,RB1
    RETFIE

STOP:
    BCF PORTB,RB0
    BCF PORTB,RB1
    RETFIE
    RETFIE
    ;ENGINE CONTROL SETTING END
END
   